trigger:
  - main
  - develop

variables:
  - name: archiveName
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}: 
      value: "OnlineSales_Admin.zip"
    ${{ else }}: 
      value: "OnlineSales_Admin_DEV.zip"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.13.0'
    displayName: 'Install Node.js'

  - script: |
      echo CORE_API=$(CORE_API) >> .env
      echo CORE_API_SWAGGER=$(CORE_API_SWAGGER) >> .env
      echo MSAL_CLIENT_ID=$(MSAL_CLIENT_ID) >> .env
      echo MSAL_AUTHORITY=$(MSAL_AUTHORITY) >> .env
    displayName: 'Create .env file'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm run build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(archiveName)'
      replaceExistingArchive: true
      displayName: 'Put files into $(archiveName)'

  - task: PublishBuildArtifacts@1
    inputs:      
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(archiveName)'
      ArtifactName: 'onlinesales_admin'
      publishLocation: 'Container'
      displayName: 'Publish $(archiveName) as build artifact'